---
- name: K3s | Disable SWAP memory
  ansible.builtin.command: >-
    swapoff --all
  when: ansible_swaptotal_mb > 0
  tags: k3s

- name: K3s | Remove swapfile from /etc/fstab
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none
  tags: k3s

- name: K3s | Install K3s v{{ k3s_release_version }}
  ansible.builtin.get_url:
    url: https://github.com/k3s-io/k3s/releases/download/v{{ k3s_release_version }}%2Bk3s1/k3s
    dest: '/usr/local/bin/k3s'
    checksum: sha256:https://github.com/k3s-io/k3s/releases/download/v{{ k3s_release_version }}%2Bk3s1/sha256sum-amd64.txt
    force: yes
    validate_certs: yes
    mode: 0755
  register: k3s_downloaded
  tags: k3s

- name: K3s | Copy k3s systemd service file
  ansible.builtin.template:
    src: k3s.service.j2
    dest: /etc/systemd/system/k3s.service
    owner: root
    group: root
    mode: 0644
  tags: k3s

- name: K3s | Enable and start k3s service
  ansible.builtin.systemd:
    name: k3s.service
    state: started
    enabled: yes
    daemon_reload: yes
  tags: k3s

- name: K3s | Create ~/.kube directory to {{ k3s_server_nonroot_user | default('ansible_user', true) }} user
  ansible.builtin.file:
    path: "/home/{{ k3s_server_nonroot_user | default('ansible_user', true) }}/.kube"
    state: directory
    owner: "{{ k3s_server_nonroot_user | default('ansible_user', true) }}"
    group: "{{ k3s_server_nonroot_user | default('ansible_user', true) }}"
    mode: 0700
  register: kubeconfig_directory_created
  tags: k3s

- name: K3s | Copy the kubeconfig file to /home/{{ k3s_server_nonroot_user | default('ansible_user', true) }}/.kube
  ansible.builtin.copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ kubeconfig_directory_created.path }}/config"
    owner: "{{ k3s_server_nonroot_user | default('ansible_user', true) }}"
    group: "{{ k3s_server_nonroot_user | default('ansible_user', true) }}"
    mode: 0600
    remote_src: yes
  tags: k3s
