---
k3s_install: true

k3s_release_version: 1.23.4

# Directory to hold state. Defaults to '/var/lib/rancher/k3s'
k3s_server_data_dir: ''

# Do not deploy packaged components and delete any deployed components (valid items: coredns, servicelb, traefik,local-storage, metrics-server)
k3s_server_disable_services:
  - servicelb
  - traefik
  - local-storage

# Network CIDR to use for pod IPs. Defaults to '10.42.0.0/16'
k3s_server_cluster_cidr: ''

# Cluster domain. Defaults to 'cluster.local'
k3s_server_cluster_domain: ''

# Non-root user to administrate cluster. Defaults to 'ubuntu'
k3s_server_nonroot_user: ''
