---
k3s_install: true

k3s_release_version: 1.23.4

# Directory to hold state. Defaults to '/var/lib/rancher/k3s'
k3s_server_data_dir: ''

# Do not deploy packaged components and delete any deployed components (valid items: coredns, servicelb, traefik,local-storage, metrics-server)
k3s_server_disable_services:
  - servicelb
  - traefik

# Default local storage path for local provisioner storage class. Defaults to '/var/lib/rancher/k3s/storage'
k3s_server_local_storage_path: ''
