---
- name: Ansible Playbook to install and configure Containerd
  hosts: all
  gather_facts: true
  any_errors_fatal: true
  become: true
  roles:
    - role: containerd
      tags:
        - containerd
