---
- name: Ansible Playbook to install and configure Kubernetes
  hosts: all
  gather_facts: true
  any_errors_fatal: true
  become: true
  roles:
    - role: kubernetes
      tags:
        - kubernetes
